docker:
  cpu:
    image: ${ASKCOS_REGISTRY}/forward_predictor/graph2smiles:1.0-cpu
    build: docker build -f Dockerfile_cpu -t ${ASKCOS_REGISTRY}/forward_predictor/graph2smiles:1.0-cpu .
    start: sh scripts/serve_cpu_in_docker.sh
  gpu:
    image: ${ASKCOS_REGISTRY}/forward_predictor/graph2smiles:1.0-gpu
    build: docker build -f Dockerfile_gpu -t ${ASKCOS_REGISTRY}/forward_predictor/graph2smiles:1.0-gpu .
    start: sh scripts/serve_gpu_in_docker.sh

singularity:
  cpu:
    image: graph2smiles_cpu.sif
    build: singularity build -f graph2smiles_cpu.sif singularity_cpu.def
    start: sh scripts/serve_cpu_in_singularity.sh
  gpu:
    image: graph2smiles_gpu.sif
    build: singularity build -f graph2smiles_gpu.sif singularity_gpu.def
    start: sh scripts/serve_gpu_in_singularity.sh

commands:
  download: sh scripts/download_trained_models.sh
  stop-docker: docker stop forward_graph2smiles
  stop-singularity: singularity instance stop forward_graph2smiles
